### ISSUE TITLE
Risk of chargebacks?

### ISSUE THREAD

**Issue by wisefool769** [zkp2p/zk-p2p#87]
The Bisq p2p Bitcoin onramping software has made the decision not to include Venmo as a payment method, due to the frequency of chargebacks
https://github.com/bisq-network/growth/issues/221

Do you have reason to expect that the zk-p2p setup is robust to these problems? 
Would the zk verification technique generalize to other payment providers?

**Comment by richardliang** [comment]
I believe there's a difference between merchant payments (purchases) and peer to peer payments on Venmo, in which the Venmo ToS is distinguishing against. Initially ZKP2P will only support only peer to peer transactions which is very difficult to reverse unless both parties agree. Other payment platforms have similar policies where nonmerchant customer payments are "irreversible"

Agree otherwise that chargebacks is a high research priority
